# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 428d57d551aebb5974444a3dcd3ff290bac38f2412a58169ac4d5bf3acac94aabfa957499ee5a623c89cd49efcbce3c687738d817d5cfa3b4467479d61bdd68f

test:
  secret_key_base: 2fbd8dc8628f7ee8957ea253918066ed1b9d3434f8f2e6f952dac4d61f934f2719e0446ea897ad12444fa5123ad567bb21bd7667666de8dbf6e9c9ce49bfaed5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
